### ISSUE TITLE
[bug]: Capitalize the First Letter of Files in the Components and Pages Folders

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#3]
I would like to request that all files inside the "components" and "pages" folders within the project be renamed with the first letter capitalized. This will ensure consistency and improve code readability throughout the application.

**Comment by vitor-barros** [comment]
Hey, i've encountered some issues while I was renaming the folders. 

1. Everytime I renamed a component I had this error: 
Module not found: Error: Cannot find file: 'footer.jsx' does not match the corresponding name on disk:
However, I was correctly renaming all the names in the project. I found a fix on stackoverflow that said to restart vscode. And it worked but I have to do this for every single component, so I don't think its pratical. 

2. When I start the project I get this error:
ERROR in [eslint] Plugin "react" was conflicted between "package.json » eslint-config-react-app
I found a fix for it, when I press CRTL + S in the package.json file it works. But I don't think its a pratical solution, (because everytime i start the project with npm it requires me to do it). 

I'm new to contributing to open source projects and react in general, so might be  my mistake too, I also would like to help with the project, I liked the idea!

**Comment by vivekrawat21** [comment]
I think you also  have to change the export statement in evey component for importing it

**Comment by Saurav-Pant** [comment]
Thanks for checking this @vitor-barros 

**1. Module not found error after renaming a component:**

When you rename a component, you need to update the corresponding import statements in other files to reflect the new name.
Look for any import statements that reference the old component name and update them accordingly.
Make sure to check both the file paths and the component names used in the imports.

**2. "Plugin 'react' was conflicted" error in ESLint:**

Open your package.json file.
In the "eslintConfig" section, add "plugin:react/recommended" to the "extends" array.
like that 
```"eslintConfig": {
  "extends": ["react-app", "plugin:react/recommended"]
},

```
By adding "plugin:react/recommended" to the "extends" array, you ensure that the "react" plugin is correctly configured and resolves the conflict. This change should eliminate the need to press CTRL + S each time you start the project.

After making this modification, try running your project again with npm start and see if the error persists.

**Comment by Saurav-Pant** [comment]
i am assigning you @vitor-barros
